In [1]:
import numpy as np

In [4]:
l = np.array([10,20,30,40,50])
t = np.array((10,20,30,40,50))
print(l)
print(type(l))
print(t)
print(type(t))

[10 20 30 40 50]
<class 'numpy.ndarray'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


In [7]:
l2 = np.array([[10,20,30,40],[50,60,70,80]])
t2 = np.array(((10,20,30,40),(50,60,70,80)))
print(l2)
print(type(l2))
print(t2)
print(type(t2))

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>


In [8]:
#x down y left to right


In [20]:
l = np.array([10,20,30,40,50,90,70],dtype=float)
t = np.array((10,20,30,40,50,70))
sum = list(map(lambda x,y : x+y, l,t))

In [21]:
print(sum)

[20.0, 40.0, 60.0, 80.0, 100.0, 160.0]


In [19]:
print(l+t)

ValueError: operands could not be broadcast together with shapes (7,) (6,) 

In [25]:
arrayone = np.array([1,2,3,4,5])
arraytwo = np.array([5,4,3,2,1])
tone = np.array((1,2,3,4))
print(arrayone)
print(arraytwo)
print(tone)

[1 2 3 4 5]
[5 4 3 2 1]
[1 2 3 4]


In [39]:
arraythree = arrayone > 2
print(arraythree)

[False False  True  True  True]


In [40]:
arrayone[arraythree]

array([3, 4, 5])

In [41]:
arrayone - arraytwo

array([-4, -2,  0,  2,  4])

In [42]:
np.ones(4)

array([1., 1., 1., 1.])

In [49]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [54]:
np.random.random([6,6])

array([[0.05034533, 0.78283637, 0.0115401 , 0.1686863 , 0.40649903,
        0.44894877],
       [0.64810659, 0.30354637, 0.1919445 , 0.28949252, 0.12376877,
        0.59574145],
       [0.3709571 , 0.81244228, 0.99940556, 0.99081999, 0.60709928,
        0.5255839 ],
       [0.88092251, 0.17447886, 0.64073148, 0.32451872, 0.63702934,
        0.01982405],
       [0.42139168, 0.60262194, 0.26598928, 0.96534819, 0.75562738,
        0.55709196],
       [0.97121769, 0.14146244, 0.09279167, 0.78734933, 0.75284963,
        0.6400177 ]])

In [76]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))

print(a , b , a + b ,end="") 

[[2 7 6]
 [3 5 4]
 [2 5 7]] [[5 3 5]
 [2 5 9]
 [6 5 5]] [[ 7 10 11]
 [ 5 10 13]
 [ 8 10 12]]

In [77]:
import time 


In [78]:
list1 = [i for i in range(200000)]
list2 = [j**2 for j in range(200000)]
start_time = time.time()
perform_ops = list(map(lambda x,y:x*y,list1,list2))
ops_time = time.time()
diff_time = ops_time - start_time
print(diff_time)

0.06823873519897461


In [79]:
ar1 = np.array([i for i in range(200000)])
ar2 = np.array([j**2 for j in range(200000)])
npstart_time = time.time()
ar3 = ar1*ar2
np_endtime = time.time()
np_dif= np_endtime - npstart_time
print(np_dif)

0.009444475173950195
