In [50]:
import numpy as np

In [7]:
s = np.arange(0,12)
print(s)
print(s.size)
print(np.resize(s,(3,6)))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


In [13]:
aa = np.arange(9).reshape(3,3)
ab = np.arange(12).reshape(3,4)
print(aa)
print()
print(ab)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
ac = np.arange(9,18).reshape(3,3)
print(np.concatenate((aa,ac)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [16]:
np.hstack((aa,ac))

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [18]:
np.vstack((aa,ac))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [19]:
print(np.r_[aa,ac])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [22]:
print(np.c_[aa,ac])

[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


In [24]:
sam = np.arange(10,20)
print(sam)

[10 11 12 13 14 15 16 17 18 19]


In [27]:
print(np.exp(sam))

[2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05
 1.20260428e+06 3.26901737e+06 8.88611052e+06 2.41549528e+07
 6.56599691e+07 1.78482301e+08]


In [28]:
np.log(sam)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [29]:
np.sin(sam)

array([-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [30]:
sam

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
fu = [(x**2+2*x+3) for x in sam]
print(fu)

[123, 146, 171, 198, 227, 258, 291, 326, 363, 402]


In [36]:
vf = np.vectorize(lambda x:(x**2+2*x+3))
vf(sam)

array([123, 146, 171, 198, 227, 258, 291, 326, 363, 402])

# Linear algebra operation

#### np.linalg.inv
#### np.linalg.det
#### np.linalg.eig
#### np.dot(a,b)

In [38]:
arr1 = np.arange(5,14).reshape(3,3)
arr2 = np.arange(1,13).reshape(3,4)
print(arr1)
print()
print(arr2)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
print(np.linalg.det(arr1))
#np.linalg.det(arr2)

0.0


In [65]:
print(np.linalg.inv(arr2))
#np.linalg.inv(arr2)

LinAlgError: Last 2 dimensions of the array must be square

In [66]:
np.linalg.eig(arr1)

(array([ 2.76509717e+01, -6.50971698e-01,  6.66880826e-16]),
 array([[-0.37636677, -0.75529416,  0.40824829],
        [-0.55798202, -0.05094566, -0.81649658],
        [-0.73959727,  0.65340284,  0.40824829]]))

In [67]:
np.dot(arr1,arr2)

array([[ 98, 116, 134, 152],
       [143, 170, 197, 224],
       [188, 224, 260, 296]])